/*
 * Copyright 2008 - 2009 Lars Heuer (heuer[at]semagia.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.tmapix.io;

import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.Arrays;

import org.xml.sax.Attributes;
import org.xml.sax.helpers.AttributesImpl;


/**
 * Simple SAX-alike XML writer.
 * 
 * @author Lars Heuer (heuer[at]semagia.com) <a href="http://www.semagia.com/">Semagia</a>
 * @version $Rev$ - $Date$
 */
final class XMLWriter {

    public static final Attributes EMPTY_ATTRS = new AttributesImpl(); 

    private static final char _NL = '\n';

    private OutputStreamWriter _out;

    private final String _encoding;

    private int _depth;

    private boolean _prettify;

    public XMLWriter(final OutputStream out) throws IOException {
        this(out, "utf-8");
    }

    public XMLWriter(final OutputStream out, final String encoding) throws IOException {
        _out = new OutputStreamWriter(out, encoding);
        _encoding = encoding;
    }

    public void setPrettify(final boolean prettify) {
        _prettify = prettify;
    }

    public boolean getPrettify() {
        return _prettify;
    }

    /**
     * @see org.xml.sax.DocumentHandler#startDocument()
     */
    public void startDocument() throws IOException {
        _out.write("<?xml version=\"1.0\" encoding=\"");
        _out.write(_encoding);
        _out.write("\" standalone=\"yes\"?>");
        _newline();
        _out.write("<!-- Generated by TMAPIX I/O - http://www.tmapix.org/ -->");
        if (!_prettify) {
            _newline();
        }
        _depth = 0;
    }

    /**
     * @see org.xml.sax.DocumentHandler#endDocument()
     */
    public void endDocument() throws IOException {
        _newline();
        try {
            _out.flush();
        }
        finally {
            _out = null;
        }
    }

    /**
     * Writes an element start with no attributes.
     */
    public void startElement(final String name) throws IOException {
        startElement(name, EMPTY_ATTRS);
    }

    /**
     * @see org.xml.sax.DocumentHandler#startElement(java.lang.String, org.xml.sax.AttributeList)
     */
    public void startElement(final String name, final Attributes attrs) throws IOException {
        _indent();
        _out.write('<');
        _out.write(name);
        _writeAttributes(attrs);
        _out.write('>');
        _depth++;
    }

    /**
     * @see org.xml.sax.DocumentHandler#endElement(java.lang.String)
     */
    public void endElement(final String name) throws IOException {
        _endElement(name, true);
    }

    private void _endElement(final String name, final boolean indent) throws IOException {
        _depth--;
        if (indent) {
            _indent();
        }
        _out.write("</");
        _out.write(name);
        _out.write('>');
    }

    public void emptyElement(final String name) throws IOException {
        emptyElement(name, EMPTY_ATTRS);
    }

    public void emptyElement(final String name, final Attributes attrs) throws IOException {
        _indent();
        _out.write('<');
        _out.write(name);
        _writeAttributes(attrs);
        _out.write("/>");
    }

    public void dataElement(final String name, final String data) throws IOException {
        dataElement(name, EMPTY_ATTRS, data);
    }

    public void dataElement(final String name, final Attributes attrs, final String data) throws IOException {
        startElement(name, attrs);
        characters(data);
        _endElement(name, false);
    }

    private void _writeAttributes(final Attributes attrs) throws IOException {
        char[] chars;
        for (int i=0; i < attrs.getLength(); i++) {
            _out.write(' ');
            _out.write(attrs.getLocalName(i));
            _out.write("=\"");
            chars = attrs.getValue(i).toCharArray();
            _writeEscapedCharacters(chars, 0, chars.length, true);
            _out.write('"');
        }
    }

    /**
     * Writes a <tt>#x0A</tt> to the output.
     *
     * @throws IOException If an error occurs.
     */
    private void _newline() throws IOException {
        _out.write(_NL);
    }

    private void _indent() throws IOException {
        if (!_prettify) {
            return;
        }
        _newline();
        final char[] chars = new char[_depth*2];
        Arrays.fill(chars, ' ');
        _out.write(chars);
    }

    /**
     * Writes the specified characters to the output.
     *
     * @param data The data to write.
     * @throws IOException If an error occurs.
     */
    public void characters(final String data) throws IOException {
        final char[] chars = data.toCharArray();
        characters(chars, 0, chars.length);
    }

    /**
     * @see org.xml.sax.DocumentHandler#characters(char[], int, int)
     */
    public void characters(final char[] chars, final int start, final int length) throws IOException {
        _writeEscapedCharacters(chars, start, length, false);
    }

    private void _writeEscapedCharacters(final char[] ch, final int start, final int length,
            final boolean attributeValue) throws IOException {
        for (int i = start; i < start + length; i++) {
            switch (ch[i]) {
            case '&':
                _out.write("&amp;");
                break;
            case '<':
                _out.write("&lt;");
                break;
            case '>':
                _out.write("&gt;");
                break;
            case '\"':
                if (attributeValue) {
                    _out.write("&quot;");
                }
                else {
                    _out.write('\"');
                }
                break;
            default:
                if (ch[i] > '\u007f') {
                    _out.write("&#");
                    _out.write(Integer.toString(ch[i]));
                    _out.write(';');
                }
                else {
                    _out.write(ch[i]);
                }
            }
        }
        
    }

}
